### ISSUE TITLE
Where to store photo's

### ISSUE THREAD

**Issue by waterkip** [waterkip/Act#10]
Act now stores photo's somewhere in the `$Config->root` folder based on
die dir_photo variable found in the configuration. This allows pictures to be stored on "normal" machines, but with Docker one would put these either Swift, S3 or on a volume in order to be able to keep the data after a container restart.

Move logic to allow for absolute paths?

**Comment by waterkip** [comment]
This would also require more code to support S3, Swift and what not.

**Comment by vanHoesel** [comment]
can we, for now, mount a photo directory, so that development can continue?

**Comment by waterkip** [comment]
I need to otherwise it breaks on a restart, I've already have a /opt/filestore volume in the docker-compose file so it should be easy to fix.

**Comment by waterkip** [comment]
Changed the logic a bit. We can save photo's now. bug #20 is open for actually showing them.

**Comment by waterkip** [comment]
Fixed.
