### ISSUE TITLE
Allow files to be placed on S3/Swift

### ISSUE THREAD

**Issue by waterkip** [waterkip/Act#15]
Easier for people who do SaaS Acts

**Comment by vanHoesel** [comment]
Eventually, that would be needed, but for now, I would suggest to create 2 (at least) environments for Docker:
- development
- production
- testing (as far as I know it uses separate databases)

 current focus being on development

**Comment by waterkip** [comment]
It is a v3 milestone, so I'm not focussing on that right now. Just a brain dump on github :)

I don't understand your dev/prod/testing things. You can use the docker image for all of those. Although, that maybe milestone v4: create nginx/apache containers which serve either the PSGI app or make use of FGCI.

**Comment by vanHoesel** [comment]
Correct me if I'm wrong, but in a dev environment I'd like to be capable to run everything locally, without the need of the internet. I will be totally happy with files stored in a shared directory. In production you typically need to have a different storage facility in the cloud and thus different config.

wouldn't those be set inside the docker-compose ?

🤔

**Comment by waterkip** [comment]
That's why I've created milestones. This thing isn't due until after my vacation in May. The first milestone is to have a working solution with Docker: https://github.com/waterkip/Act/milestone/1

**Comment by waterkip** [comment]
Migrated to https://github.com/act-psgi/Act/issues/17
