### ISSUE TITLE
Make testsuite work

### ISSUE THREAD

**Issue by waterkip** [waterkip/Act#16]
This is kind of a stupid requirement, I know, but very much needed.

This seems to be more work. 

* There are some tests that test the setup of your current installation and not the code itself. This needs to go IMO. The code needs to work as expected. The testsuite shouldn't validate that you have a working installation, this should be done in the code by die-ing early and validating the configuration on startup.

* There are some tests that check all the dependencies, this can be automated via dzil for example to generate a Makefile.PL and a cpanfile

* The tests use t/Util.pm, move to t/lib and use Test::Lib for those instances

* Maybe create t/lib/Act.pm and put some sane defaults in there (use Test::More or Most) and be done, reduces boilerplating in .t files

**Comment by vanHoesel** [comment]
👍 that would be awesome !!!

**Comment by waterkip** [comment]
More people agree: https://github.com/act-psgi/Act/issues/11
