### ISSUE TITLE
Not all static files are shown

### ISSUE THREAD

**Issue by waterkip** [waterkip/Act#21]
Any static file found in wwwdocs aren't show to the user.

**Comment by HaraldJoerg** [comment]
Hi Wesley,

perhaps you are struggling with the same issue as I did: https://github.com/HaraldJoerg/Act/issues/1
In the comment over there I've shown the directory structure which works with the PSGI engine.  It is not the same as described in the installation guide of the master branch.

**Comment by waterkip** [comment]
I made it work, think I pushed the changes as well. The problem is in Act::Dispatch code. See 2e02ea16f39df5eecef42d65d12795950bb8ac38
