### ISSUE TITLE
Create seperate database for the wiki

### ISSUE THREAD

**Issue by waterkip** [waterkip/Act#7]
We can run one DB server on a docker instance. But the loading becomes a bit annoying due to the environment variable of the database in docker. 

We can work around it by scripting it, but it would still require us to do some scripting based on configuration files found elsewhere...

What do the Act guys do in the real world? I think we should opt for multiple databases instances, but feel uncertain about it. What to do?

**Comment by vanHoesel** [comment]
yes, we run a separate database for the Wiki

**Comment by waterkip** [comment]
Awesome, so I'll make a second DB server for the wiki.

**Comment by vanHoesel** [comment]
I think that won't hurt :-)
