### ISSUE TITLE
Change directory layout for conferences

### ISSUE THREAD

**Issue by waterkip** [waterkip/Act#8]
Right now the conferences (https://github.com/Act-Conferences) have a pretty standard directory layout. Within Act itself these directories are split into other bits and pieces

```
$ tree -d nlpw2018
nlpw2018
├── actdocs
│   ├── conf
│   ├── static
│   │   └── tutorials
│   └── templates
│       ├── core
│       │   ├── bank
│       │   └── user
│       ├── custom
│       ├── menus
│       ├── payment
│       ├── texts
│       ├── tutorials
│       └── user
└── wwwdocs
├── css
└── img
```

Act (afaik) splits this up to:
```
actdocs => $ACT_HOME/actdocs/nlpw2018/
wwwdocs => $ACT_HOME/wwwdocs/nlpw2018
```

This is kinda bothersome in Docker, since you don't want to mount two folders for each conference (or, I wouldn't at least).

**Comment by vanHoesel** [comment]
For the current development, I rather not change these directories, dozens of conferences are currently build on that structure.

For development I would suggest to have 1 folder on the host, called `conferences` and have that mount into the docker container.

Have a script that at start up time will scan the directory for existing repos (yes, those are independent repos and should remain as such) and create two symbols-links from `$ACT_HOME/actdocs/$repo_name` --> `conferences/$repo_name/actdocs`, same for the `wwwdocs`

**Comment by vanHoesel** [comment]
Oh... and it should link to a checkout of `master` on those repos, usually

**Comment by vanHoesel** [comment]
As far as I know, it are the French devops that actually have to do some manual setup to get it all working. It's not just a matter of creating a new repo at Act-Conferences. There needs to be some database setup too. You need to have an existing and authorised Act-User to add assistant admins, like treasurer and wiki maintainers etc.

**Comment by waterkip** [comment]
I actually want to keep the directory structure that is present in all the act conferences repo. But I need to make it work with plack. Which is the actual troublesome thing. But while I was running I thought of a solution that should work. The issue is that the wwwdocs are served by NginX/Apache - whatever webserver they use. So, that should go to the wwwdocs. Then you have plack, which doesn't know anything right now about these wwwdocs and isn't serving them. So that needs to be working if you want a simple docker container where things just work.

I'm not sure if those who run act (I think it is centralized somewhere?) if and when they use Docker on how they are going to use them.

The thing is that it probably falls back to the generic wwwdocs if it cannot find something in the conference wwwdocs directory?

**Comment by vanHoesel** [comment]
btw, I truly hope that the last two (css and img) are inside wwwdocs.

It probably does need some setup to route conference names or domain names to directories on the Apache server.

**Comment by waterkip** [comment]
Serving the static files can now be done via plack, this one can be closed.
