### ISSUE TITLE
PSGI or not (which branch becomes leading master or PSGI)

### ISSUE THREAD

**Issue by waterkip** [waterkip/Act#9]
The PSGI branch is a bit out of date with the master branch:

```
On branch psgi
Your branch and 'upstream/master' have diverged,
and have 143 and 196 different commits each, respectively.
```

What branch should become leading?

**Comment by vanHoesel** [comment]
@waterkip , I hope I did all the merges right...

You can find a fully merged version of book/act-master, book/act-psgi plus the ilya/act-psgi_fixes at the Act-Voyager project repository. The PSGI + FIXES are rebased onto master, and hopefully something nice came out of it.

The Act-Voyager/act-psgi branch should probably be your leading branch for a dockerized PSGI implementation

The Act Voyager repo is where all projects are, currently, with useful info and rubbish info too

**Comment by waterkip** [comment]
I've just rebased on master with all the psgi fixes from @ichesnokov, see the `act-two` branch

**Comment by vanHoesel** [comment]
I trust you know what you're doing --- Since I do not know the implementation details, I just hope and pray it will at least do the basics, fixes can come later

**Comment by waterkip** [comment]
You can run it if you want :) The biggest problem is the testsuite that is broken on master/psgi/psgi-fixes and thus my own branches.

**Comment by waterkip** [comment]
Hold on, so book/Act isn't the correct upstream?

**Comment by vanHoesel** [comment]
for the time being ... not really, the Act-Voyager should be upstream, but merging from book/Act can't hurt.

once there are working implementations on  Act-Voyager/Act and other related topics there, then it will become a curated merge / replacement.

Creating a dockerized PSGI version is one of those implementations that can than be proposed to the Act Devpos in France. That requires a bit more than just a PR

**Comment by waterkip** [comment]
I see. They don't need to dockerize if they don't want to. They can deploy it via other means as well. But having docker allows devs to easily test things. I don't see a dependency for the devops in France to have docker. I'll have a go at the other upstream then.

**Comment by vanHoesel** [comment]
hmmm... correct, deploying is a different thing. But what I tried to get across is that the work you have been busy with, is more than just a PR, it requires the French DevOps to do quite a bit of more work than just merging a PR etc.

THANKS ...

I AM EXCITED

**Comment by waterkip** [comment]
Well, have a go, I think the `act-two` branch is ready for testing by someone else. I seem to have nlwp2018 working. So... works for me (tm).

**Comment by waterkip** [comment]
TODO: Need to investigate the changes from git@github.com:Act-Voyager/Act.git in my branch and rebase

**Comment by vanHoesel** [comment]
Ah ... that explains why the diff shows some removals of previously fixed issues :-)

**Comment by vanHoesel** [comment]
I hope I is branched of the Act-Voyager/Act@psgi version? and not master! And maybe the ichesnokov/Act@psgi_fixes would have been an even better starting point.

Difference is that the Act-Voyager has an un-tested version rebased on the fully merged current Book/Act@master into Act-Voyager/Act@master

Taken the Ilya psgi_fixes as starting point means gradually applying the changes made in Book/Act@master.

But in any .... no branching of any of the master branches

**Comment by waterkip** [comment]
I don't follow. But I can tell you what I did.

Branched of psgi, merged branch from Ilya, worked on it a bit to make it dockery. Rebased on book/master. Now I need to see how I can cleanly apply Act-Voyager/master in my branch (which is the TODO a few lines up).

**Comment by vanHoesel** [comment]
Ah ... First three are great! up to and including 'make it docker'. Rebasing on book/master would indeed take it all the way to the latest changes - and probably causing quite a few conflicts. Since current Act-Voyager/master has Book Master merged, I wouldn't see any problems there.

**Comment by vanHoesel** [comment]
exciting!

**Comment by waterkip** [comment]
Using act-psgi as a main fork is now a fact
